version: '3.8'

services:
  web:
    image: ghcr.io/carte-toronto/carte-website:latest
    container_name: carte-web
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - carte-net

  beta:
    image: ghcr.io/carte-toronto/carte-website:beta
    container_name: carte-beta
    restart: unless-stopped
    networks:
      - carte-net
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://localhost/" ]
      interval: 30s
      timeout: 10s
      retries: 3

  neighbourhoods:
    image: ghcr.io/uoft-carte/toronto-neighbourhoods:latest
    container_name: carte-neighbourhoods
    restart: unless-stopped
    networks:
      - carte-net
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://localhost/" ]
      interval: 30s
      timeout: 10s
      retries: 3

  subscribe-api:
    image: ghcr.io/carte-toronto/carte-website-subscribe-api:latest
    container_name: carte-subscribe-api
    restart: unless-stopped
    env_file: .env
    networks:
      - carte-net

volumes:
  caddy_data:
  caddy_config:


networks:
  carte-net:
    driver: bridge
